apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taraxa-info-api.fullname" . }}
  labels: {{- include "taraxa-info-api.labels" . | nindent 4 }}
data:
  TOKEN_ADDRESS: {{ .Values.app.tokenAddress | quote }}
  NODE_ENV: {{ .Values.app.environment | quote }}
  TARA_PROVIDER: {{ .Values.app.taraProvider | quote }}
  STAKING_ADDRESS: {{ .Values.app.stakingAddress | quote }}
  DEPLOYER_ADDRESS: {{ .Values.app.deployerAddress | quote }}
  MAINNET_DPOS_CONTRACT_ADDRESS: {{ .Values.app.taraDposAddress | quote }}
  DELEGATION_API_ROOT_URI: {{ .Values.app.mainnetDelegationUri | quote }}
  COINGECKO_API_TARAXA_URI: {{ .Values.app.coingeckoUri | quote }}
  TESTNET_EXPLORER_API_ROOT_URI: {{ .Values.app.testnetExplorerUri | quote }}
  REDIS_HOST: {{ .Values.app.redisHost | quote }}
  REDIS_PORT: {{ .Values.app.redisPort | quote }}
  REDIS_NAME: {{ .Values.app.redisName | quote }}
  NAME_PREFIX: {{ .Values.app.namePrefix | quote }}
  ROOT_URI: {{ .Values.app.rootUri | quote }}
