apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.environment }}-{{ include "taraxa-info-api.fullname" . }}
  labels:
    {{- include "taraxa-info-api.labels" . | nindent 4 }}
data:
  TOKEN_ADDRESS: {{ .Values.app.tokenAddress | quote }}
  NODE_ENV: {{ .Values.app.environment | quote }}
