apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.app.environment }}-{{ include "taraxa-info-api.fullname" . }}
  labels:
    {{- include "taraxa-info-api.labels" . | nindent 4 }}
data:
  PROVIDER: {{ .Values.app.provider | quote }}