apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "taraxa-info-api.fullname" . }}
  labels: {{- include "taraxa-info-api.labels" . | nindent 4 }}
data:
  PROVIDER: {{ .Values.app.provider | b64enc | quote }}
  GITHUB_ACCESS_TOKEN: {{ .Values.app.githubToken | b64enc | quote }}
