apiVersion: v1
kind: Service
metadata:
  name: {{ include "taraxa-info-api.fullname" . }}
  labels:
    {{- include "taraxa-info-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.serverPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "taraxa-info-api.selectorLabels" . | nindent 4 }}
