app:
  environment: production
  tokenAddress: 0xf001937650bb4f62b57521824b2c20f5b91bea05
  taraProvider: https://rpc.mainnet.taraxa.io/
  stakingAddress: 0x7Af59Ea121a8Da8e49d2d44856feB7761561995b
  deployerAddress: 0x723304D1357A2334FCf902Aa3d232f5139080A1b
  taraDposAddress: 0x00000000000000000000000000000000000000fe
  mainnetDelegationUri: https://api-delegation.community.taraxa.io
  coingeckoUri: https://api.coingecko.com/api/v3/simple/price?ids=taraxa&vs_currencies=usd
  testnetIndexerUri: https://indexer.testnet.taraxa.io
  mainnetIndexerUri: https://indexer.mainnet.taraxa.io
  redisHost: 10.39.114.21
  redisPort: 6379
  redisPassword: pass
  redisName: infocache

image:
  tag: "latest"
  pullPolicy: Always

nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-prod

ingress:
  hosts:
    - host: api.taraxa.io
  tls:
    - secretName: wild-api-taraxa-io-tls
      hosts:
        - api.taraxa.io

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 125m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
